# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'
  mbedDirectory: '$(Build.SourcesDirectory)\targets\mbedOS'
  nfSrcDirectory: '$(Build.SourcesDirectory)\src'

steps:
  - script: |
      echo switching to $(parameters.mbedDirectory)
      cd $(parameters.mbedDirectory)
      mbed new .
      echo switching to $(parameters.buildDirectory)
      cd $(parameters.buildDirectory)
      echo todo - add macros e.g. -DUVISOR_PRESENT
      echo todo - add nf directories
      mbed compile -m K64F -t GCC_ARM -vv --sources $(parameters.mbedDirectory)
      mbed config --list
    displayName: 'build target using mbed-cli'
