# Copyright (c) 2019 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'
  mbedDirectory: '$(Build.SourcesDirectory)\targets\mbedOS'
  nfSrcDirectory: '$(Build.SourcesDirectory)\src'

steps:
  - script: |
      mkdir $(Build.SourcesDirectory)\build

      :: TODO - currently having problems adding multiple sources, so for the moment we will hack it
      :: by just copying the source required into its own folder

      mkdir $(Build.SourcesDirectory)\mbedProject
      cd $(Build.SourcesDirectory)\mbedProject
      xcopy $(Build.SourcesDirectory)\targets\mbedOS /e
      xcopy $(Build.SourcesDirectory)\src /e
      
      mbed new .
      mbed config --list
      
      echo todo - add macros e.g. -DUVISOR_PRESENT
      echo todo - add nf directories
      mbed compile -m K64F -t GCC_ARM -vv --source . --build $(Build.SourcesDirectory)\build
    displayName: 'build target using mbed-cli'
