# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(parameters.SourceDirectory)\src\targets\mbedOS'

steps:
  - script: |
      mbed import $(parameters.buildDirectory)
      cd $(parameters.buildDirectory)
      echo todo... run command - mbed compile -m K64F -t ARM
      mbed config --list
    displayName: 'build target using mbed-cli'
