# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  builDirectory: '$(Build.SourcesDirectory)\build'

steps:
  - script: |
      mbed config --list
    displayName: 'build target using mbed-cli'
