# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: repoDirectory
    type: string
    default: $(Build.SourcesDirectory)

steps:

  - template: setup-cmake-user-presets.yml
    parameters:
      repoDirectory: ${{ parameters.repoDirectory }}

  - task: CMake@1
    inputs:
      cmakeArgs: '--preset $(CMakePreset) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_NAME=$(TargetPublishName) -DTOOL_SRECORD_PREFIX=$(SRECORD_PATH)/srecord/ $(BuildOptions)'
      workingDirectory:  ${{ parameters.repoDirectory }}
    displayName: Setup build with CMake

  - task: CMake@1
    inputs:
      cmakeArgs: '--build --preset $(CMakePreset) --target all --config MinSizeRel'
      workingDirectory:  ${{ parameters.repoDirectory }}
    displayName: Build with CMake
