# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'
  mbedDirectory: '$(Build.SourcesDirectory)\targets\mbedOS'
  nfSrcDirectory: '$(Build.SourcesDirectory)\src'

steps:
  - script: |
      :: echo switching to $(Build.SourcesDirectory)\targets\mbedOS
      :: cd $(Build.SourcesDirectory)\targets\mbedOS
      :: echo switching to $(Build.SourcesDirectory)\build
      mkdir $(Build.SourcesDirectory)\build
      cd $(Build.SourcesDirectory)\build
      
      mbed new .
      mbed config --list
      
      echo todo - add macros e.g. -DUVISOR_PRESENT
      echo todo - add nf directories
      mbed compile -m K64F -t GCC_ARM -vv --sources $(Build.SourcesDirectory)\targets\mbedOS $(Build.SourcesDirectory)\src
    displayName: 'build target using mbed-cli'
