# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: repoDirectory
    type: string
    default: $(Build.SourcesDirectory)

steps:
  - task: PowerShell@2
    displayName: Set target publish package name
    inputs:
      targetType: "inline"
      script: |
        $packageName = if(-not [string]::IsNullOrEmpty($env:PackageName)) { $env:PackageName } else { $env:PACKAGENAME }
        $targetBoard = if(-not [string]::IsNullOrEmpty($env:TargetBoard)) { $env:TargetBoard } else { $env:TARGETBOARD }

        if([string]::IsNullOrEmpty($packageName))
        {
          Write-Host "$("##vso[task.setvariable variable=TargetPublishName]")$targetBoard"
        }
        else
        {
          Write-Host "$("##vso[task.setvariable variable=TargetPublishName]")$packageName"
        }
      errorActionPreference: "stop"
      failOnStderr: true

  - task: PowerShell@2
    displayName: Add dummy cmake presets
    condition: ne(variables['Build.Repository.Name'], 'nanoframework/nf-Community-Targets')
    inputs:
      workingDirectory: ${{ parameters.repoDirectory }}/targets-community
      targetType: "inline"
      script: |
        New-Item -Path . -Name "CMakePresets.json" -ItemType "file" -Value "{`n""version"": 4,`n""include"": []`n}"
