# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'
  mbedDirectory: '$(Build.SourcesDirectory)\src\targets\mbedOS'
  nfCLRDirectory: '$(Build.SourcesDirectory)\src\CLR'
  nfHALDirectory: '$(Build.SourcesDirectory)\src\HAL'
  nfPALDirectory: '$(Build.SourcesDirectory)\src\PAL'
  nfDevIfDirectory: '$(Build.SourcesDirectory)\src\DeviceInterfaces'

steps:
  - script: |
      cd $(parameters.mbedDirectory)
      mbed new .
      cd $(parameters.buildDirectory)
      echo todo - add macros e.g. -DUVISOR_PRESENT
      echo todo - add nf directories
      mbed compile -m K64F -t GCC_ARM -vv --sources $(parameters.mbedDirectory)
      mbed config --list
    displayName: 'build target using mbed-cli'
