# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'

steps:

  - task: CMake@1
    displayName: Setup CMake (DFU, no SRecord)
    condition: and(eq(variables['NeedsDFU'], true), eq(variables['NeedsSRECORD'], 'false'))
    inputs:
      cmakeArgs: '-G Ninja -DCMAKE_TOOLCHAIN_FILE=CMake/toolchain.arm-none-eabi.cmake -DTOOLCHAIN_PREFIX=$(GNU_GCC_TOOLCHAIN_PATH) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_BOARD=$(TargetBoard) -DTARGET_NAME=$(TargetPublishName) -DTOOL_HEX2DFU_PREFIX=$(HEX2DFU_PATH) $(BuildOptions) ..'
      workingDirectory:  ${{ parameters.buildDirectory }}

  - task: CMake@1
    displayName: Setup CMake build (SRecord, no DFU)
    condition: and(eq(variables['NeedsSRECORD'], true), eq(variables['NeedsDFU'], false))
    inputs:
      cmakeArgs: '-G Ninja -DCMAKE_TOOLCHAIN_FILE=CMake/toolchain.arm-none-eabi.cmake -DTOOLCHAIN_PREFIX=$(GNU_GCC_TOOLCHAIN_PATH) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_BOARD=$(TargetBoard) -DTARGET_NAME=$(TargetPublishName) -DTOOL_SRECORD_PREFIX=$(SRECORD_PATH)/srecord/ $(BuildOptions)  ..'
      workingDirectory:  ${{ parameters.buildDirectory }}

  - task: CMake@1
    displayName: Setup CMake build (DFU and SRecord)
    condition: and(eq(variables['NeedsDFU'], true), eq(variables['NeedsSRECORD'], true))
    inputs:
      cmakeArgs: '-G Ninja -DCMAKE_TOOLCHAIN_FILE=CMake/toolchain.arm-none-eabi.cmake -DTOOLCHAIN_PREFIX=$(GNU_GCC_TOOLCHAIN_PATH) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_BOARD=$(TargetBoard) -DTARGET_NAME=$(TargetPublishName) -DTOOL_HEX2DFU_PREFIX=$(HEX2DFU_PATH) -DTOOL_SRECORD_PREFIX=$(SRECORD_PATH)/srecord/ $(BuildOptions) ..'
      workingDirectory:  ${{ parameters.buildDirectory }}

  - task: CMake@1
    displayName: Setup CMake build (no DFU, no SRecord)
    condition: and(eq(variables['NeedsDFU'], false), eq(variables['NeedsSRECORD'], false))
    inputs:
      cmakeArgs: '-G Ninja -DCMAKE_TOOLCHAIN_FILE=CMake/toolchain.arm-none-eabi.cmake -DTOOLCHAIN_PREFIX=$(GNU_GCC_TOOLCHAIN_PATH) -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION=$(NBGV_VersionMajor).$(NBGV_VersionMinor).$(NBGV_BuildNumber).$(TARGET_BUILD_COUNTER) -DTARGET_BOARD=$(TargetBoard) -DTARGET_NAME=$(TargetPublishName) $(BuildOptions) ..'
      workingDirectory:  ${{ parameters.buildDirectory }}

  - task: CMake@1
    displayName: Build with CMake
    inputs:
      cmakeArgs: '--build ${{ parameters.buildDirectory }} --target all --config MinSizeRel'
      workingDirectory:  ${{ parameters.buildDirectory }}
