# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: repoDirectory
    type: string
    default: $(Agent.BuildDirectory)/s

steps:

  - task: Cache@2
    displayName: Cache IDF repository
    inputs:
      key: 'esp-idf | "$(IDF_TAG)"'
      path: $(Agent.BuildDirectory)/s/esp-idf
      cacheHitVar: ESP32_IDF_REPO_RESTORED

  - task: PowerShell@2
    displayName: Checkout IDF repository
    condition: ne(variables.ESP32_IDF_REPO_RESTORED, 'true')
    inputs:
      targetType: "inline"
      script: |
        # Set error action preference to stop on any error
        $ErrorActionPreference = "Stop"
        
        Write-Host "Creating directory at ${{ parameters.repoDirectory }}"
        
        # create directory for IDF, ignore if it already exists
        New-Item -Path ${{ parameters.repoDirectory }} -ItemType "directory" -ErrorAction SilentlyContinue

        Write-Host "Changing to directory ${{ parameters.repoDirectory }}"
        
        # move to the build sources directory
        Set-Location -Path ${{ parameters.repoDirectory }}

        Write-Host "Cloning ESP-IDF repository (tag: $(IDF_TAG))..."
        
        $cloneArgs = @(
          'clone',
          '--recurse-submodules',
          '--shallow-submodules',
          '--single-branch',
          '--depth', '1',
          '--branch', '$(IDF_TAG)',
          '--progress',
          'https://github.com/espressif/esp-idf'
        )

        $output = & git @cloneArgs 2>&1

        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to clone ESP-IDF repository:`n$output"
          exit 1
        }

        Write-Host "Successfully cloned ESP-IDF repository"
