# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - bash: |
      sudo apt-get install -y srecord
      mkdir -p "$(Agent.TempDirectory)/srecord/srecord"
      for f in /usr/bin/srec_*; do ln -sf "$f" "$(Agent.TempDirectory)/srecord/srecord/"; done
      echo "##vso[task.setvariable variable=SRECORD_PATH]$(Agent.TempDirectory)/srecord"
    displayName: Install SRECORD
    condition: eq(variables['NeedsSRECORD'], true)
