# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: cmakeVersion
    type: string
    default: "3.31.6"

steps:
  - task: Cache@2
    inputs:
      key: 'cmake-3_31_6'
      path: $(System.DefaultWorkingDirectory)/choco_cache/cmake
    displayName: 'Cache CMake installation'

  - script: |
      cmake --version
      choco install cmake --version=${{ parameters.cmakeVersion }} --force --yes --cache $(System.DefaultWorkingDirectory)/choco_cache/cmake
      cmake --version
    displayName: 'Force Install CMake ${{ parameters.cmakeVersion }}'
