# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: Cache@2
    inputs:
      key: '1-0 | hex2dfuKey'
      restoreKeys: hex2dfuKey
      path: $(Agent.TempDirectory)/hex2dfu
      cacheHitVar: HEX2DFU_CACHE_RESTORED
    condition: eq(variables['NeedsDFU'], true)
    displayName: Cache HEX2DFU

  - task: PowerShell@2
    condition: and( eq(variables['NeedsDFU'], true), ne(variables.HEX2DFU_CACHE_RESTORED, 'true'))
    displayName: Install HEX2DFU
    inputs:
        targetType: 'filePath'
        filePath: 'install-scripts\install-nf-hex2dfu.ps1'
        failOnStderr: 'true'

  - task: PowerShell@2
    inputs:
        targetType: 'inline'
        script: |
            $newPath = "$env:Agent_TempDirectory".Replace('\','/') + "/hex2dfu"
            Write-Host "$("##vso[task.setvariable variable=HEX2DFU_PATH]")$newPath"
        errorActionPreference: 'stop'
        failOnStderr: 'true'
    condition: eq(variables['NeedsDFU'], true)
    displayName: Adjust HexDFU path
