# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: Cache@2
    condition: ne(variables['System.PullRequest.PullRequestId'], '')
    displayName: Cache LLVM
    inputs:
      key: "llvm_18_1_7_linux | llvmUpdateKey"
      restoreKeys: llvmUpdateKey-linux
      path: $(Agent.TempDirectory)/llvm
      cacheHitVar: LLVM_CACHE_RESTORED

  - bash: |
      mkdir -p $(Agent.TempDirectory)/llvm/bin
      sudo apt-get install -y clang-format-18
      cp /usr/bin/clang-format-18 "$(Agent.TempDirectory)/llvm/bin/clang-format"
      chmod +x "$(Agent.TempDirectory)/llvm/bin/clang-format"
    displayName: Install clang-format
    condition: >-
      and(
        ne(variables['System.PullRequest.PullRequestId'], ''),
        ne(variables.LLVM_CACHE_RESTORED, 'true')
      )

  - script: |
      echo ##vso[task.prependpath]$(Agent.TempDirectory)/llvm/bin
    displayName: Add LLVM to PATH
    condition: ne(variables['System.PullRequest.PullRequestId'], '')
