# Copyright (c) 2019 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: PowerShell@2
    inputs:
        targetType: 'inline'
        script: |
            Write-Host "Downloading SRecord..."
            $url = "https://sourceforge.net/projects/srecord/files/srecord-win32/1.64/srecord-1.64-win32.zip/download"
            $output = "$env:Agent_TempDirectory\srecord.zip"
            (New-Object Net.WebClient).DownloadFile($url, $output)
        errorActionPreference: 'stop'
        failOnStderr: 'true'
    condition: eq(variables['NeedsSRECORD'], true)
    displayName: Install SRECORD

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)\srecord.zip' 
      destinationFolder: '$(Agent.TempDirectory)\srecord' 
    displayName: Extract SRECORD

  - task: PowerShell@2
    inputs:
        targetType: 'inline'
        script: |
            $newPath = "$env:Agent_TempDirectory".Replace('\','/')
            Write-Host "$("##vso[task.setvariable variable=SRECORD_PATH]")$newPath"
        errorActionPreference: 'stop'
        failOnStderr: 'true'
    condition: eq(variables['NeedsSRECORD'], true)
    displayName: Adjust SRECORD path