# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  # cache IDF tools folder
  - task: Cache@2
    displayName: Cache ESP32 tools
    inputs:
      key: 'esp32_tools | "$(IDF_TAG)"'
      path: $(Pipeline.Workspace)/.espressif/tools
      cacheHitVar: ESP32_TOOLS_CACHE_RESTORED

  # cache pip packages
  - task: Cache@2
    displayName: Cache pip packages
    inputs:
      key: 'python | "$(Agent.OS)" | $(Agent.BuildDirectory)/s/esp-idf/tools/requirements/requirements.core.txt'
      restoreKeys: python | "$(Agent.OS)" | $(Agent.BuildDirectory)/s/esp-idf/tools/requirements/requirements.core.txt
      path: $(PIP_CACHE_DIR)
      cacheHitVar: PIP_PACKAGES_RESTORED

  # Use Python Version 3.11 and add it to path
  - task: UsePythonVersion@0
    displayName: Set Python to v3.11
    inputs:
      versionSpec: "3.11"
      addToPath: true

  # run IDF installer
  - bash: |
      export IDF_TOOLS_PATH=$(Pipeline.Workspace)/.espressif
      echo "##vso[task.setvariable variable=IDF_TOOLS_PATH]$(Pipeline.Workspace)/.espressif"
      cd $(Agent.BuildDirectory)/s/esp-idf
      git config core.autocrlf false
      git checkout -- .
      bash install.sh all
    displayName: Install IDF

  - bash: |
      python -m pip install -r $(Agent.BuildDirectory)/s/esp-idf/tools/requirements/requirements.core.txt
    displayName: Install IDF pip requirements (step 1)

  - bash: |
      python -m pip install --quiet -r "$(Agent.BuildDirectory)/s/nf-interpreter/requirements.txt"
    displayName: Install nF Kconfig tools

  - bash: |
      export IDF_TOOLS_PATH=$(Pipeline.Workspace)/.espressif
      source $(Agent.BuildDirectory)/s/esp-idf/export.sh > /dev/null 2>&1
      echo "$PATH" | tr ':' '\n' | tac | while IFS= read -r p; do
        echo "##vso[task.prependpath]$p"
      done
    displayName: Update PATH with IDF tools

  - bash: |
      python -m pip install --quiet -r "$(Agent.BuildDirectory)/s/nf-interpreter/requirements.txt"
    displayName: Install kconfiglib in IDF Python
