//
// Copyright (c) 2020 The nanoFramework project contributors
// See LICENSE file in the project root for full license information.
//

#include "net_thread_native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeCreateStack___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeSetActiveDataset___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeGetActiveDataset___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeJoinerStart___VOID__STRING,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeStartThread___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeStopThread___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeDispose___VOID,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeSendConsoleInput___VOID__STRING__BOOLEAN,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeGetConsoleOutput___SZARRAY_STRING,
    Library_net_thread_native_nanoFramework_Networking_Thread_OpenThread::NativeGetMeshLocalAddress___SZARRAY_U1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Networking_Thread =
{
    "nanoFramework.Networking.Thread",
    0x4EF1F92D,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
