//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

#include "nf_system_collections.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Hashtable::Clear___VOID,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Hashtable::InsertNative___VOID__OBJECT__OBJECT__BOOLEAN__I4,
    Library_nf_system_collections_System_Collections_Hashtable::GetNative___OBJECT__OBJECT__I4,
    Library_nf_system_collections_System_Collections_Hashtable::ContainsNative___BOOLEAN__OBJECT__I4,
    Library_nf_system_collections_System_Collections_Hashtable::RemoveNative___VOID__OBJECT__I4,
    Library_nf_system_collections_System_Collections_Hashtable::GetPrimeNative___STATIC__I4__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Hashtable__HashtableEnumerator::MoveNext___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Queue::Clear___VOID,
    Library_nf_system_collections_System_Collections_Queue::CopyTo___VOID__SystemArray__I4,
    Library_nf_system_collections_System_Collections_Queue::Enqueue___VOID__OBJECT,
    NULL,
    Library_nf_system_collections_System_Collections_Queue::Dequeue___OBJECT,
    Library_nf_system_collections_System_Collections_Queue::Peek___OBJECT,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Stack::Clear___VOID,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_system_collections_System_Collections_Stack::Peek___OBJECT,
    Library_nf_system_collections_System_Collections_Stack::Pop___OBJECT,
    Library_nf_system_collections_System_Collections_Stack::Push___VOID__OBJECT,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_System_Collections =
{
    "nanoFramework.System.Collections",
    0x40DC251F,
    method_lookup,
    { 100, 0, 2, 0 }
};

// clang-format on
