//
// Copyright (c) .NET Foundation and Contributors
// Portions Copyright (c) Microsoft Corporation.  All rights reserved.
// See LICENSE file in the project root for full license information.
//

#include "sys_io_ser_native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::get_BytesToRead___I4,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::get_InvertSignalLevels___BOOLEAN,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::set_InvertSignalLevels___VOID__BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::Read___I4__SZARRAY_U1__I4__I4,
    NULL,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::ReadExisting___STRING,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::ReadLine___STRING,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::Write___VOID__SZARRAY_U1__I4__I4,
    NULL,
    NULL,
    NULL,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::NativeDispose___VOID,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::NativeInit___VOID,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::NativeConfig___VOID,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::NativeSetWatchChar___VOID,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::NativeWriteString___VOID__STRING__BOOLEAN,
    NULL,
    NULL,
    Library_sys_io_ser_native_System_IO_Ports_SerialPort::GetDeviceSelector___STATIC__STRING,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_IO_Ports =
{
    "System.IO.Ports",
    0xCB7C0ECA,
    method_lookup,
    { 100, 1, 4, 0 }
};

// clang-format on
