//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

// POSIX host nf_config.h.
// On embedded targets this file is generated by the Kconfig pipeline at build time.
// Here we manually define the set of CONFIG_* symbols consumed by shared source
// files, mirroring the feature set of the Windows (win32 / VIRTUAL_DEVICE) host.

#ifndef NF_CONFIG_H
#define NF_CONFIG_H

// ── Build options ─────────────────────────────────────────────────────────────
// Use native double-precision floating point.
#define CONFIG_NF_ENABLE_DOUBLE_PRECISION_FP 1
// Full math library.
#define CONFIG_NF_FEATURE_LIGHT_MATH 0
// String-to-any-base conversion.
#define CONFIG_NF_SUPPORT_ANY_BASE_CONVERSION 1

// ── nanoFramework features ────────────────────────────────────────────────────
// Managed application debugging transport present.
#define CONFIG_NF_FEATURE_DEBUGGER 1
// System.Reflection API.
#define CONFIG_NF_FEATURE_SUPPORT_REFLECTION 1
// Binary serialization support.
#define CONFIG_NF_FEATURE_BINARY_SERIALIZATION 1

// ── nanoFramework APIs ────────────────────────────────────────────────────────
// nanoFramework.System.Collections — enables CLR_RT_HeapBlock_Stack/Queue.
#define CONFIG_API_NANOFRAMEWORK_SYSTEM_COLLECTIONS 1

#endif // NF_CONFIG_H
