// Licensed to the .NET Foundation under one or more agreements.
// See LICENSE file in the project root for full license information.

#ifndef TARGET_OS_H
#define TARGET_OS_H

// Substitute for the Kconfig-generated nf_config.h value.
// The check in nanoHAL_Boot.h and nanoHAL_Capabilites.h requires this symbol
// to be defined; the actual value is unused by those guards.
#define CONFIG_RTOS POSIX_HOST

#define TARGET_HAS_NANOBOOTER 0

// Firmware version — taken from version.json (1.16.0.0).
// On real targets these are generated by CMake from a .h.in template.
#ifndef VERSION_MAJOR
#define VERSION_MAJOR    1U
#endif
#ifndef VERSION_MINOR
#define VERSION_MINOR    16U
#endif
#ifndef VERSION_BUILD
#define VERSION_BUILD    0U
#endif
#ifndef VERSION_REVISION
#define VERSION_REVISION 0U
#endif

#define TARGETINFOSTRING "POSIX Debug build"

// Feature and API configuration (replaces the Kconfig-generated nf_config.h).
#include "nf_config.h"

#endif // TARGET_OS_H
