//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "windows_devices_gpio_provider_native.h"
#include "windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider.h"

using namespace Windows::Devices::Gpio::Provider;


HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::get_DebounceTimeout___mscorlibSystemTimeSpan( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        //UNSUPPORTED_TYPE retVal = DefaultGpioPinProvider::get_DebounceTimeout( pMngObj,  hr );
        signed int retVal = (signed int) DefaultGpioPinProvider::get_DebounceTimeout( pMngObj,  hr );
        NANOCLR_CHECK_HRESULT( hr );
        
        //SetResult_UNSUPPORTED_TYPE( stack, retVal );
        SetResult_INT32( stack, retVal );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::set_DebounceTimeout___VOID__mscorlibSystemTimeSpan( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        UNSUPPORTED_TYPE param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UNSUPPORTED_TYPE( stack, 1, param0 ) );

        DefaultGpioPinProvider::set_DebounceTimeout( pMngObj,  param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeWrite___VOID__I4__U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param0 ) );

        unsigned char param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 2, param1 ) );

        DefaultGpioPinProvider::NativeWrite( pMngObj,  param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeRead___WindowsDevicesGpioProviderProviderGpioPinValue__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param0 ) );

        signed int retVal = DefaultGpioPinProvider::NativeRead( pMngObj,  param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retVal );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeSetDriveMode___VOID__I4__WindowsDevicesGpioProviderProviderGpioPinDriveMode( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 2, param1 ) );

        DefaultGpioPinProvider::NativeSetDriveMode( pMngObj,  param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeOpenpin___BOOLEAN__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param0 ) );

        bool retVal = DefaultGpioPinProvider::NativeOpenpin( pMngObj,  param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_bool( stack, retVal );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeIsDriveModeSupported___BOOLEAN__U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        unsigned char param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8( stack, 1, param0 ) );

        bool retVal = DefaultGpioPinProvider::NativeIsDriveModeSupported( pMngObj,  param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_bool( stack, retVal );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeDispose___VOID( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        DefaultGpioPinProvider::NativeDispose( pMngObj,  hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}
