//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _WINDOWS_DEVICES_GPIO_PROVIDER_NATIVE_H_
#define _WINDOWS_DEVICES_GPIO_PROVIDER_NATIVE_H_

#include <nanoCLR_Interop.h>
struct Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioControllerProvider
{
    static const int FIELD_STATIC__SOMETHING_WRONG_WITH_THIS_FIELD_POSSIBLY_MISSING_BACKING_FIELD = 0;

    NANOCLR_NATIVE_DECLARE(get_PinCount___I4);

    //--//

};

struct Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider
{
    static const int FIELD___disposed = 1;
    static const int FIELD___pinDriveMode = 2;
    static const int FIELD___pinNumber = 3;

    NANOCLR_NATIVE_DECLARE(get_DebounceTimeout___mscorlibSystemTimeSpan);
    NANOCLR_NATIVE_DECLARE(set_DebounceTimeout___VOID__mscorlibSystemTimeSpan);
    NANOCLR_NATIVE_DECLARE(NativeWrite___VOID__I4__U1);
    NANOCLR_NATIVE_DECLARE(NativeRead___WindowsDevicesGpioProviderProviderGpioPinValue__I4);
    NANOCLR_NATIVE_DECLARE(NativeSetDriveMode___VOID__I4__WindowsDevicesGpioProviderProviderGpioPinDriveMode);
    NANOCLR_NATIVE_DECLARE(NativeOpenpin___BOOLEAN__I4);
    NANOCLR_NATIVE_DECLARE(NativeIsDriveModeSupported___BOOLEAN__U1);
    NANOCLR_NATIVE_DECLARE(NativeDispose___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Gpio_Provider;

#endif  //_WINDOWS_DEVICES_GPIO_PROVIDER_NATIVE_H_
