//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "windows_devices_gpio_provider_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioControllerProvider::get_PinCount___I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::get_DebounceTimeout___mscorlibSystemTimeSpan,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::set_DebounceTimeout___VOID__mscorlibSystemTimeSpan,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeWrite___VOID__I4__U1,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeRead___WindowsDevicesGpioProviderProviderGpioPinValue__I4,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeSetDriveMode___VOID__I4__WindowsDevicesGpioProviderProviderGpioPinDriveMode,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeOpenpin___BOOLEAN__I4,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeIsDriveModeSupported___BOOLEAN__U1,
    Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioPinProvider::NativeDispose___VOID,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Gpio_Provider =
{
    "Windows.Devices.Gpio.Provider", 
    0x076B5B40,
    method_lookup
};

