//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "windows_devices_gpio_provider_native.h"
#include "windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioControllerProvider.h"

using namespace Windows::Devices::Gpio::Provider;


HRESULT Library_windows_devices_gpio_provider_native_Windows_Devices_Gpio_Provider_DefaultGpioControllerProvider::get_PinCount___I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_HeapBlock* pMngObj = Interop_Marshal_RetrieveManagedObject( stack );

        FAULT_ON_NULL(pMngObj);

        signed int retVal = DefaultGpioControllerProvider::get_PinCount( pMngObj,  hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retVal );

    }
    NANOCLR_NOCLEANUP();
}
