//
// Copyright (c) .NET Foundation and Contributors
// Portions Copyright (c) 2006..2015 Giovanni Di Sirio. All rights reserved.
// See LICENSE file in the project root for full license information.
//

#ifndef MCUCONF_H
#define MCUCONF_H

// clang-format off

/*
 * STM32F7xx MCU configuration for the MCUboot bootloader on ORGPAL_PALTHREE.
 *
 * Derived from targets/ChibiOS/ORGPAL_PALTHREE/nanoBooter/mcuconf.h.
 * Clock settings are identical (HSE 12 MHz, PLLM=6, PLLN=216 → 216 MHz SYSCLK).
 * Only the SPI1 peripheral is enabled; all USB, SERIAL, WSPI entries are
 * disabled to keep code size minimal.
 */

#define STM32F7xx_MCUCONF
#define STM32F769_MCUCONF

/*
 * Memory attributes settings.
 */
#define STM32_NOCACHE_ENABLE                FALSE

/*
 * HAL driver system settings — clock identical to nanoBooter.
 */
#define STM32_NO_INIT          FALSE
#define STM32_PVD_ENABLE       FALSE
#define STM32_PLS              STM32_PLS_LEV0
#define STM32_BKPRAM_ENABLE    TRUE
#define STM32_HSI_ENABLED      TRUE
#define STM32_LSI_ENABLED      TRUE
#define STM32_HSE_ENABLED      TRUE
#define STM32_LSE_ENABLED      TRUE
#define STM32_CLOCK48_REQUIRED TRUE
#define STM32_SW               STM32_SW_PLL
#define STM32_PLLSRC           STM32_PLLSRC_HSE
#define STM32_PLLM_VALUE       6
#define STM32_PLLN_VALUE       216
#define STM32_PLLP_VALUE       2
#define STM32_PLLQ_VALUE       9
#define STM32_PLLR_VALUE       2
#define STM32_HPRE             STM32_HPRE_DIV1
#define STM32_PPRE1            STM32_PPRE1_DIV4
#define STM32_PPRE2            STM32_PPRE2_DIV2
#define STM32_RTCSEL           STM32_RTCSEL_LSE
#define STM32_RTCPRE_VALUE     25
#define STM32_MCO1SEL          STM32_MCO1SEL_HSI
#define STM32_MCO1PRE          STM32_MCO1PRE_DIV1
#define STM32_MCO2SEL          STM32_MCO2SEL_SYSCLK
#define STM32_MCO2PRE          STM32_MCO2PRE_DIV1
#define STM32_TIMPRE_ENABLE    FALSE
#define STM32_I2SSRC           STM32_I2SSRC_OFF
#define STM32_PLLI2SN_VALUE    192
#define STM32_PLLI2SP_VALUE    2
#define STM32_PLLI2SQ_VALUE    2
#define STM32_PLLI2SR_VALUE    2
#define STM32_PLLI2SDIVQ_VALUE 1
#define STM32_PLLSAIN_VALUE    192
#define STM32_PLLSAIP_VALUE    2
#define STM32_PLLSAIQ_VALUE    2
#define STM32_PLLSAIR_VALUE    2
#define STM32_PLLSAIDIVQ_VALUE 1
#define STM32_PLLSAIDIVR_VALUE 2
#define STM32_SAI1SEL          STM32_SAI1SEL_OFF
#define STM32_SAI2SEL          STM32_SAI2SEL_OFF
#define STM32_LCDTFT_REQUIRED  FALSE
#define STM32_USART1SEL        STM32_USART1SEL_PCLK2
#define STM32_USART2SEL        STM32_USART2SEL_PCLK1
#define STM32_USART3SEL        STM32_USART3SEL_PCLK1
#define STM32_UART4SEL         STM32_UART4SEL_PCLK1
#define STM32_UART5SEL         STM32_UART5SEL_PCLK1
#define STM32_USART6SEL        STM32_USART6SEL_PCLK2
#define STM32_UART7SEL         STM32_UART7SEL_PCLK1
#define STM32_UART8SEL         STM32_UART8SEL_PCLK1
#define STM32_I2C1SEL          STM32_I2C1SEL_PCLK1
#define STM32_I2C2SEL          STM32_I2C2SEL_PCLK1
#define STM32_I2C3SEL          STM32_I2C3SEL_PCLK1
#define STM32_I2C4SEL          STM32_I2C4SEL_PCLK1
#define STM32_LPTIM1SEL        STM32_LPTIM1SEL_PCLK1
#define STM32_CECSEL           STM32_CECSEL_HSIDIV488
#define STM32_CK48MSEL         STM32_CK48MSEL_PLL
#define STM32_SDMMC1SEL        STM32_SDMMC1SEL_PLL48CLK
#define STM32_SDMMC2SEL        STM32_SDMMC2SEL_PLL48CLK
#define STM32_SRAM2_NOCACHE    FALSE

/*
 * IRQ system settings.
 */
#define STM32_IRQ_EXTI0_PRIORITY     6
#define STM32_IRQ_EXTI1_PRIORITY     6
#define STM32_IRQ_EXTI2_PRIORITY     6
#define STM32_IRQ_EXTI3_PRIORITY     6
#define STM32_IRQ_EXTI4_PRIORITY     6
#define STM32_IRQ_EXTI5_9_PRIORITY   6
#define STM32_IRQ_EXTI10_15_PRIORITY 6
#define STM32_IRQ_EXTI16_PRIORITY    6
#define STM32_IRQ_EXTI17_PRIORITY    15
#define STM32_IRQ_EXTI18_PRIORITY    6
#define STM32_IRQ_EXTI19_PRIORITY    6
#define STM32_IRQ_EXTI20_PRIORITY    6
#define STM32_IRQ_EXTI21_PRIORITY    15
#define STM32_IRQ_EXTI22_PRIORITY    15
#define STM32_IRQ_EXTI23_PRIORITY    6

#define STM32_IRQ_USART1_PRIORITY 12
#define STM32_IRQ_USART2_PRIORITY 12
#define STM32_IRQ_USART3_PRIORITY 12
#define STM32_IRQ_UART4_PRIORITY  12
#define STM32_IRQ_UART5_PRIORITY  12
#define STM32_IRQ_USART6_PRIORITY 12
#define STM32_IRQ_UART7_PRIORITY  12
#define STM32_IRQ_UART8_PRIORITY  12

/*
 * SPI driver system settings — SPI1 enabled for AT25SF641 external flash.
 * DMA streams and priorities copied from nanoBooter mcuconf.h.
 */
#define STM32_SPI_USE_SPI1             TRUE
#define STM32_SPI_USE_SPI2             FALSE
#define STM32_SPI_USE_SPI3             FALSE
#define STM32_SPI_USE_SPI4             FALSE
#define STM32_SPI_USE_SPI5             FALSE
#define STM32_SPI_USE_SPI6             FALSE
#define STM32_SPI_SPI1_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 0)
#define STM32_SPI_SPI1_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 3)
#define STM32_SPI_SPI2_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 3)
#define STM32_SPI_SPI2_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 4)
#define STM32_SPI_SPI3_RX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 0)
#define STM32_SPI_SPI3_TX_DMA_STREAM   STM32_DMA_STREAM_ID(1, 7)
#define STM32_SPI_SPI4_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 0)
#define STM32_SPI_SPI4_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 1)
#define STM32_SPI_SPI5_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 3)
#define STM32_SPI_SPI5_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 4)
#define STM32_SPI_SPI6_RX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 6)
#define STM32_SPI_SPI6_TX_DMA_STREAM   STM32_DMA_STREAM_ID(2, 5)
#define STM32_SPI_SPI1_DMA_PRIORITY    1
#define STM32_SPI_SPI2_DMA_PRIORITY    1
#define STM32_SPI_SPI3_DMA_PRIORITY    1
#define STM32_SPI_SPI4_DMA_PRIORITY    1
#define STM32_SPI_SPI5_DMA_PRIORITY    1
#define STM32_SPI_SPI6_DMA_PRIORITY    1
#define STM32_SPI_SPI1_IRQ_PRIORITY    10
#define STM32_SPI_SPI2_IRQ_PRIORITY    10
#define STM32_SPI_SPI3_IRQ_PRIORITY    10
#define STM32_SPI_SPI4_IRQ_PRIORITY    10
#define STM32_SPI_SPI5_IRQ_PRIORITY    10
#define STM32_SPI_SPI6_IRQ_PRIORITY    10
#define STM32_SPI_DMA_ERROR_HOOK(spip) osalSysHalt("DMA failure")

/*
 * ST driver system settings.
 */
#define STM32_ST_IRQ_PRIORITY 8
#define STM32_ST_USE_TIMER    2

/*
 * SERIAL driver — all disabled (no debug UART in the MCUboot bootloader).
 */
#define STM32_SERIAL_USE_USART1 FALSE
#define STM32_SERIAL_USE_USART2 FALSE
#define STM32_SERIAL_USE_USART3 FALSE
#define STM32_SERIAL_USE_UART4  FALSE
#define STM32_SERIAL_USE_UART5  FALSE
#define STM32_SERIAL_USE_USART6 FALSE
#define STM32_SERIAL_USE_UART7  FALSE
#define STM32_SERIAL_USE_UART8  FALSE

/*
 * USB driver — disabled.
 */
#define STM32_USB_USE_OTG1 FALSE
#define STM32_USB_USE_OTG2 FALSE

/*
 * WSPI driver — disabled (PALTHREE uses SPI1, not QUADSPI).
 */
#define STM32_WSPI_USE_QUADSPI1             FALSE
#define STM32_WSPI_QUADSPI1_DMA_STREAM      STM32_DMA_STREAM_ID(2, 7)
#define STM32_WSPI_QUADSPI1_PRESCALER_VALUE 2

/*
 * WDG driver — disabled.
 */
#define STM32_WDG_USE_IWDG FALSE

// nanoFramework overlay driver settings
#include "mcuconf_nf.h"

#endif /* MCUCONF_H */

// clang-format on
