# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This PS installs the ARM GNU GCC toolchain from our Cloudsmith repository if it's not already available

[CmdletBinding(SupportsShouldProcess = $true)]
param (
    [Parameter(HelpMessage = "Path to the folder where the tool is to be installed.")][string]$Path,
    [Parameter(HelpMessage = "GNU GCC version requested.")][string]$Version,
    [switch]$force = $false
)

# set default GNU GCC version
if ([string]::IsNullOrEmpty($Version)) {
    $Version = "13.3.rel1"
}

# check if running on Azure Pipelines by looking at this two environment variables
$IsAzurePipelines = $env:Agent_HomeDirectory -and $env:Build_BuildNumber

if ($IsAzurePipelines) {
    $zipRoot = "$env:Agent_TempDirectory"
}
else {
    #Set location of nf-interpreter top-level
    $nfRoot = "$PSScriptRoot\.."
    $zipRoot = "$nfRoot\zips"

    # Create directory for zip files if necessary
    mkdir -Force $zipRoot | Out-Null
}

if ([string]::IsNullOrEmpty($Path) -or $force) {
    # no path requested
    # check for NF_TOOLS_PATH
    if ($env:NF_TOOLS_PATH) {
        $toolPath = $env:NF_TOOLS_PATH
    }
    else {
        # use default
        $toolPath = 'C:\nftools'
    }

    # append the tool path
    $toolPath = $toolPath + "\GNU_Tools_ARM_Embedded\$Version"
}

# check if path already exists
$gnuGccPathExists = Test-Path $toolPath -ErrorAction SilentlyContinue    

# download, if needed
If ($gnuGccPathExists -eq $False -or $force) {
    $url = "https://developer.arm.com/-/media/Files/downloads/gnu/" + $Version + "/binrel/arm-gnu-toolchain-" + $Version + "-mingw-w64-i686-arm-none-eabi.zip"
    $output = "$zipRoot\arm-gnu-toolchain-" + $Version + "-mingw-w64-i686-arm-none-eabi.zip"

    # Don't download again if already exists
    if (![System.IO.File]::Exists($output) -or $force) {
        "Download URL is: '$url'" | Write-Host -ForegroundColor White

        "Downloading ARM GNU GCC toolchain..." | Write-Host -ForegroundColor White -NoNewline
            
        # download Zip with toolchain
        (New-Object Net.WebClient).DownloadFile($url, $output)

        "OK" | Write-Host -ForegroundColor Green
    }

    # unzip to tool path, if not on Azure
    if ($IsAzurePipelines -eq $False) {

        "Installing ARM GNU GCC toolchain..." | Write-Host -ForegroundColor White -NoNewline

        # unzip toolchain
        Expand-Archive $output -DestinationPath $toolPath > $null

        # update tool path to include versioned toolchain folder
        $toolPath = $toolPath + "\arm-gnu-toolchain-" + $Version + "-mingw-w64-i686-arm-none-eabi"

        "OK" | Write-Host -ForegroundColor Green
    }
}
else {
    "Skipping install of ARM GNU GCC toolchain" | Write-Host -ForegroundColor Yellow
}

# set env variable, if not on Azure
if ($IsAzurePipelines -eq $False) {
    # need to replace forward slash for paths to work with GCC and CMake
    $toolPath = "$toolPath".Replace('\', '/')

    "Setting User Environment Variable ARM_GCC_PATH='" + $env:ARM_GCC_PATH + "'" | Write-Host -ForegroundColor Yellow

    $env:ARM_GCC_PATH = $toolPath

    try {
        # this call can fail if the script is not run with appropriate permissions
        [System.Environment]::SetEnvironmentVariable("ARM_GCC_PATH", $env:ARM_GCC_PATH, "User")
    }
    catch {
        "Failed to set User Environment Variable ARM_GCC_PATH. Make sure to manually add 'ARM_GCC_PATH' with '" + $env:ARM_GCC_PATH + "'." | Write-Host -ForegroundColor Red
    }
}

# SIG # Begin signature block
# MIIvfQYJKoZIhvcNAQcCoIIvbjCCL2oCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBu2Wlc5nF3AiDl
# vf9gsXLLwOg/d1VWHEPI0d7lgnMHsqCCE7wwggVkMIIDTKADAgECAhAGzuExvm1V
# yAf3wMf7ROYgMA0GCSqGSIb3DQEBDAUAMEwxCzAJBgNVBAYTAlVTMRcwFQYDVQQK
# Ew5EaWdpQ2VydCwgSW5jLjEkMCIGA1UEAxMbRGlnaUNlcnQgQ1MgUlNBNDA5NiBS
# b290IEc1MB4XDTIxMDExNTAwMDAwMFoXDTQ2MDExNDIzNTk1OVowTDELMAkGA1UE
# BhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMSQwIgYDVQQDExtEaWdpQ2Vy
# dCBDUyBSU0E0MDk2IFJvb3QgRzUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
# AoICAQC2M3OA2GIDcBQsERw5XnyufIOGHf4mL0wkrYvqg1+pvD1b/AuYTAJHMOzi
# /uzoNFtmXr871yymJf+MWbPf6tp8KdlGUHIIHW7RGwrdH82ZifoPD3PE4ZwddTLN
# b5faKmqVsmzJCdDqC3t9FwZJme/W3uDIU9SuxnfxhrsjHLjA31n3jn3R74LmJota
# OLX/ddWy2U8J8zeIUNoRpIoUFNFTBAB982pEGP5QcDIHHKiaDjodxQofbgsmabc8
# oldwLIb6TG6VqVhDuawS1v8/7ddDF2tMzp7EkKv/+hBQmqOQV9bnjBCunxYazzUd
# f9d27YqcNacouKddIfwwN93eCBlPFcbnptqQR473lFNMjlMCvv2Z5eqG0K8DAtOb
# qpPxqyiOIAH/TPvMtylA9YekEhMFH0Nu11FQnzi0IO0XCRKPzLkZr5/NvmkR069V
# EG0XhnmWUsayAJ3lrziwNfSIa48OBD187q/N02oQSsbNhsoiPaFKXPsO/4jfXGKn
# wLke2axsfjg3/neTJcKFik+1NwZaBoEU8c6UnZmR6jJazmc9bgRmrQxPLaMu9571
# eJ33Cv1+j+NCilWWvPGfNy38nl+V/owYG/yO/UuQr9cDaBJjrOKTp6LLBOVPZM4D
# +sYUn9mL6MzUYoxr5AAsGZ8aBsYxgVT7UySar1WZup11rrjC3QIDAQABo0IwQDAd
# BgNVHQ4EFgQUaAGTsdJKQEJplEYsHFqIqSW0R08wDgYDVR0PAQH/BAQDAgGGMA8G
# A1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEMBQADggIBAJL87rgCeRcCUX0hxUln
# p6TxqCQ46wxo6lpCa5z0c8FpSi2zNwVQQpiSngZ5LC4Gmfbv3yugzbOSAYO1oMsn
# tTwjGphJouwtmaVZQ6zSsZPWV9ccvJPWxkDhs28ZVbcT1+VDM6S1q8vawTFkDXTW
# LO3DjW7ru68ZR2FhLcD0BblveNw690JAZVORvZkNk5JUpqk3WSuby5nGvD33BITw
# lDMdD4JaOcsuRcMoGaOym5jI/DFrYI/26YYovOA8fXRdFolbaSTHEIvES7s2T9RZ
# P8OwpJGZ+C7RSgGd9YgS779aEWpZT1lrWmfzj7QTD8DYLz0ocqoZfxF9alufledf
# t5RP8T6hWv8tzJ3fJ3ePMnMcZwp28/pcsb+8Hb0MKJuyxxdnCzMPw7023Pu6Qgur
# 7YTDYtaEFqmxB2upbu7Gz+awRCnC8LNhgCqLb9IUXCWHVGTzpEzBofina+r+6jr8
# edsOj9zG88nUbN7pg6GOHSLsyTqyAHvcO6dCGn/ci6kRPY6nwCBvXQldQ0Tmj2bM
# qVsH8e+beg6zVOGU/Q4sxpPXVf1xmDW4CUr/xikoLPZSLdsUGJIn4hZ+jMrUYb6C
# h5HrmDc/v19ddz80rBs4Q6tocpkyHjoaGaWjOEwj16PnzNUqkheQC1pLvRa9+4Zq
# 4omZ7OSgVRjJowgfE+AyCHLQMIIGkDCCBHigAwIBAgIQCt4y6VCbRKo0sdrxvA7I
# czANBgkqhkiG9w0BAQsFADBMMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNl
# cnQsIEluYy4xJDAiBgNVBAMTG0RpZ2lDZXJ0IENTIFJTQTQwOTYgUm9vdCBHNTAe
# Fw0yMTA3MTUwMDAwMDBaFw0zMTA3MTQyMzU5NTlaMFsxCzAJBgNVBAYTAlVTMRgw
# FgYDVQQKEw8uTkVUIEZvdW5kYXRpb24xMjAwBgNVBAMTKS5ORVQgRm91bmRhdGlv
# biBQcm9qZWN0cyBDb2RlIFNpZ25pbmcgQ0EyMIICIjANBgkqhkiG9w0BAQEFAAOC
# Ag8AMIICCgKCAgEAznkpxwyD+QKdO6sSwPBJD5wtJL9ncyIlhHFM8rWvU5lCCoMp
# 9TcAiXvCIIaJCeOxjXFv0maraGhSr8SANVefC74HBfDTAl/JyoWmOfBxRY/30/0q
# ivfUtoxrw91SR3Gu3eucWxxb4b+hoIpTgbKU+//cnSvi8EmBTk7ntfFkAWw/6Lov
# +nMXU+qEzm/TuCT8qWX2IffLkdXIt4UqQS8Jqjxn7cGLhjqDA9w+5zXpSxSu/JhK
# OecY05XcdGlGnQBPc8RBzUD3ZzXMPoPBSFiH7UZs23iVmVXCJoU9IFaN3WSLD/jZ
# 3TXE8RxJxoY1DODwr4t6kTSQdDPrx3aPrtAcJFblh3JMP0SpZZpV8DHALVZkKKfF
# u2SOL9Wv57MJ6M/mhfyUot2vLVxVlWlplgwOhcHP7a40cVBczF/cAb+IBz+tuB1q
# wGGi4B3qnE2kpYju6xYz75hVcfFqXGmy3+NMZIF6oMJUSLUZmU7HUDCUyMgHt6SP
# 42r7vzRyPJEMXARiNwe5jI6oAWxyeX6dN4ZXiBDa1lVaVuK8yUd7ShbETPbTPaZ5
# BaV/yxcl1rqExPqKzIH+y/a6F33KXSYVGTSFcg/tSEd4vuXbBUuIf2UpPVkK+J2/
# 0J/o8sBSkF3nFZ/USwrvcMKEiINKokHvmivypLkhSfMIEismXSO6rke8ElECAwEA
# AaOCAV0wggFZMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFCgOTIkcmZfx
# gfCPCN5XEku8uHjPMB8GA1UdIwQYMBaAFGgBk7HSSkBCaZRGLBxaiKkltEdPMA4G
# A1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEFBQcDAzB5BggrBgEFBQcBAQRt
# MGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggrBgEF
# BQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0Q1NSU0E0
# MDk2Um9vdEc1LmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5kaWdp
# Y2VydC5jb20vRGlnaUNlcnRDU1JTQTQwOTZSb290RzUuY3JsMBwGA1UdIAQVMBMw
# BwYFZ4EMAQMwCAYGZ4EMAQQBMA0GCSqGSIb3DQEBCwUAA4ICAQA66iJQhuBqWcn+
# rukrkzv8/2CGpyWTqoospvt+Nr2zsgl1xX97v588lngs94uqlTB90YLR4227PZQz
# HQAFEs0K0/UNUfoKPC9DZSn4xJxjPsLaK8N+l4d6oZBAb7AXglpxfk4ocrzM0KWY
# Tnaz3+lt0uGi8VgP8Wggh24FLxzxxiC5SqwZ7wfU7w1g7YugDn6xbcH4+yd6ZpCn
# MDcxYkGKqOtjM7V3bd3Rbl/PDySZ+chy/n6Q6ZNj9Oz/WFYlYOId7CMmI5SzbMWp
# qbdwvPNkrSYwFRtnRV9rwJo/q9jctfwrG9FQBkHMXiLHRQPw4oEoROk0AYCm26zv
# dEqc1pPCIEQHtXyOW+GqX2MORRdiePFfmG8b1xlIw8iBJOorlbEJA6tvOpDTb1I5
# +ph6tM4DwrMrS0LbGPJv0ah9fh26ZPta1xF0KC4/gdyqY7Bmij+X+atdrRZ0jdqc
# SHspWYc9U6SaXWKVXFwvkc0b19dkzECS7ebrPQuC0+euLpvDMzHIafzL21XHB1+g
# ncuwbt7/RknJoDbFKsx5x0qDQ6vfJmrajyNAMd5fGQdgcUHs75G+KWvg7M4RtGRq
# 6NHrXnBg1LHQlRbLDSCXbIoXkywzzksKuxxm9sn2gdz0/v4o4vPQHrxk8Mj6i23U
# 6h97uJQWVPhLWhQtcjc8MJmU2i5xlDCCB7wwggWkoAMCAQICEAIxmw9vuH3F75Lk
# NzIvo/AwDQYJKoZIhvcNAQELBQAwWzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTDy5O
# RVQgRm91bmRhdGlvbjEyMDAGA1UEAxMpLk5FVCBGb3VuZGF0aW9uIFByb2plY3Rz
# IENvZGUgU2lnbmluZyBDQTIwHhcNMjMxMjA2MDAwMDAwWhcNMjYxMjA4MjM1OTU5
# WjCB+zETMBEGCysGAQQBgjc8AgEDEwJVUzEbMBkGCysGAQQBgjc8AgECEwpXYXNo
# aW5ndG9uMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2FuaXphdGlvbjEUMBIGA1UEBRML
# NjAzIDM4OSAwNjgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMS4wLAYDVQQKEyUuTkVUIE5hbm8gRnJhbWV3b3JrICgu
# TkVUIEZvdW5kYXRpb24pMS4wLAYDVQQDEyUuTkVUIE5hbm8gRnJhbWV3b3JrICgu
# TkVUIEZvdW5kYXRpb24pMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# lsjv+rp18PKloMxGocKTMBfb1z1yvu/X4tCSDv7XQUjjIKdpFThtqy95p6HJFOi4
# bxHSz1UKk4Mf6VurKMkVhn63NqNAxavePPUcmnvOwxr3zuLYpeNMjHEJLcc8N5U3
# VzxZK9d/0MSQD/rfIXjdn47BImAG7ZrVJ1HAKMAOOQauoj3ZAxwd2Dnd+IbzDIP/
# glXG0+K9FGhf3oXrAUwvCCO+iTintYE8wiuxLav3UlyLoa8wOJCo2FiCsy+E9IGJ
# Zu9J2kUUbrwVihfD3fnqd6p097hCgy8n8SGl+t219LaAKwEUzQzC3XexbZU2dZrP
# 2XhFxCWDEfFgGA9f1N3Du6POy96eplqa9jOatfREIh98GzFMnJlzhPU+RMENpYfn
# khKbhYlb53rlcadT7RUcQf75qHsZNM6FMg9OLuEbPc1Ajjx1bzyTshK3cTRNzWPA
# 7PnxUMYh+TVbc8LX80+Txz1C3I4sn60mbGHJId2q8yTvi6kAoHk0a9KmjG1luR7e
# ri6VByKByxL06dPH6LMkAJoXdJ8zM5uGexNp4hJaoiGlWKQTA30IqvBRx+UYU4eW
# /+e78Karc8MbfV+cqu8CWaHtTtTU9xi6yAXS+773U1QsCzFnKbk2dZndaW0/tOo+
# VWbxbrNIZfOJSxWjTD6Xq484yLfLmw20A2ZCzfOB5hUCAwEAAaOCAdkwggHVMB8G
# A1UdIwQYMBaAFCgOTIkcmZfxgfCPCN5XEku8uHjPMB0GA1UdDgQWBBTCoK04Wcn9
# ZlPugnBrFvcTgHjANzA9BgNVHSAENjA0MDIGBWeBDAEDMCkwJwYIKwYBBQUHAgEW
# G2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCB4AwEwYD
# VR0lBAwwCgYIKwYBBQUHAwMwgZsGA1UdHwSBkzCBkDBGoESgQoZAaHR0cDovL2Ny
# bDMuZGlnaWNlcnQuY29tL05FVEZvdW5kYXRpb25Qcm9qZWN0c0NvZGVTaWduaW5n
# Q0EyLmNybDBGoESgQoZAaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL05FVEZvdW5k
# YXRpb25Qcm9qZWN0c0NvZGVTaWduaW5nQ0EyLmNybDCBhQYIKwYBBQUHAQEEeTB3
# MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wTwYIKwYBBQUH
# MAKGQ2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9ORVRGb3VuZGF0aW9uUHJv
# amVjdHNDb2RlU2lnbmluZ0NBMi5jcnQwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsF
# AAOCAgEAH9LTVkatT8HyjgCH2d2/YIjTmchnqi+eTiTJdzH2XRmoTeAu6RoaWdUL
# cImpmkvmvAY1C+7oejdVPbF3Zloq8SLvuYiHs/Typr8+uA+DBukwBWqVuAY6B1N6
# +cgz+xPQXza7fE9YzPZ5b/x39uCEljNa7EH0BP4HBETgwKmPjxkfy+vNdIY7wV7I
# FrtqlLt73XshXXs32Uozay01PoclicRHYX58sjXZw6SC0cQpBVx0/2usfBaVYV5u
# ezwL9rABe4/6Xu4E98fOub8NVrbDOYcB3AN8oXZHQLFjpDZ0+ucYepeidpvHeQDn
# xlSvoDzJR9uSA9t77S17qzn1E7+adK8DwYsLbI9/CmGSPRMlUrTvbpMWCUULr3t9
# s47AHWAP0TwUcETfxvRgleyheKjNh1pNVDSku2ZXniJ/GGsJ8dBr5KkuG6sjd2Ga
# jd8tIqV6xcj/xLUqfI/xzow2xauZQuJKoQEVxRDc9y4yfwyRLfglLPccfv29p79x
# In1tAV2yKofy7gQHoHQrtQyQHFP2hdihEpu78/GrSmaRhevFFzwPzov22tQPlPQZ
# jyV4FQw6PYDm37gPhsVwEacUA4+noUx7Ki8QyVDDMwLCgKSCId9TwBWSwAVFIh4I
# QVJ0Yz+oqfELvQae3H6R25/9oYj0YVE0XetN74GHqVELv2NzOOMxghsXMIIbEwIB
# ATBvMFsxCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw8uTkVUIEZvdW5kYXRpb24xMjAw
# BgNVBAMTKS5ORVQgRm91bmRhdGlvbiBQcm9qZWN0cyBDb2RlIFNpZ25pbmcgQ0Ey
# AhACMZsPb7h9xe+S5DcyL6PwMA0GCWCGSAFlAwQCAQUAoIHOMBkGCSqGSIb3DQEJ
# AzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8G
# CSqGSIb3DQEJBDEiBCDVyOe7XbEvLzc0EtMiQgTIiev+H8PjcNT4LYHyTfqP2zBi
# BgorBgEEAYI3AgEMMVQwUqAsgCoAbgBhAG4AbwBGAHIAYQBtAGUAdwBvAHIAawAg
# AHMAYwByAGkAcAB0AHOhIoAgaHR0cHM6Ly9naXRodWIuY29tL25hbm9GcmFtZXdv
# cmswDQYJKoZIhvcNAQEBBQAEggIALv4C90oIGnoNLLHe1rZjMV4xRchJpQzL7WPA
# TEbxxbvHEj1RqpTQHwXjNTwJQezWKgnUDb2x19RyEOz/3PfcnKoVQ6D2nm6WLYHr
# WY1IcxqcUpYnVf6AS9rPoZ5u0HFNyPYmmzMCUnoGPrBeCCpJm+1XXfeGLbkEKRoM
# IzGTjgTQ758qOdJxHEytFndVFN/4T/fe+WLPh9EtSSUXibn8EdAOkiZd7KiQFukS
# e27iD3f6vrZtW+cHuN8rvjaMiTWGG9cXs3CQDQmmd3T/SfE6gzbD5h6GWZ+ZwssU
# 8lbrOuZ50RSlHSw/hMvdwL6H9m8aSF/RvfQlAX9v/6C27FkikwLw9Q30FKDKws0M
# 5rBq4BFZTOh6E2dhZAuvC3bTjv4A2316Tn0WocdkJcM9bpbIygASIx2Uhui6y9tQ
# tFFO9M2qc7XSR5Sf3DyENugcylx56i0sDNmy8eizyA/GKCf11AOTeDHiHIUclOJk
# hPm6AgXhIxmmXY1IrOKGgN3uVYto6PwtGp00qgOXi70lNFlSQCHg1/ebjjpHVcOL
# UZG4PJDrY5CVwqDSiAWKR7ifxk1/AKk90zef0GBoar8uoA/OCfjezvnp5CRVhEhB
# vTCes8Vl+QOFKrVhx1GYCIH/MQIDbpMCEJjwKfk9bgqqTNpRATBpoMZI7qJmq+f0
# 2IvSNiWhgheoMIIXpAYKKwYBBAGCNwMDATGCF5QwgheQBgkqhkiG9w0BBwKggheB
# MIIXfQIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBaQYLKoZIhvcNAQkQAQSgggFYBIIB
# VDCCAVACAQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQgArwnKjrslHW5
# j+yGrlQD1+bY1FP4rDrPSTKT1bCvLysCBmaZCYNzNxgTMjAyNDA4MDcxMzUxMTEu
# MjEzWjAEgAIB9KCB6KSB5TCB4jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBM
# aW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpGNUQ2LTk2RDYtOTA5RTE1
# MDMGA1UEAxMsTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGltZSBTdGFtcGluZyBBdXRo
# b3JpdHmggg8oMIIHgjCCBWqgAwIBAgITMwAAAAXlzw//Zi7JhwAAAAAABTANBgkq
# hkiG9w0BAQwFADB3MQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMUgwRgYDVQQDEz9NaWNyb3NvZnQgSWRlbnRpdHkgVmVyaWZpY2F0
# aW9uIFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMjAwHhcNMjAxMTE5MjAz
# MjMxWhcNMzUxMTE5MjA0MjMxWjBhMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWlj
# cm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUHVibGljIFJT
# QSBUaW1lc3RhbXBpbmcgQ0EgMjAyMDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
# AgoCggIBAJ5851Jj/eDFnwV9Y7UGIqMcHtfnlzPREwW9ZUZHd5HBXXBvf7KrQ5cM
# SqFSHGqg2/qJhYqOQxwuEQXG8kB41wsDJP5d0zmLYKAY8Zxv3lYkuLDsfMuIEqvG
# YOPURAH+Ybl4SJEESnt0MbPEoKdNihwM5xGv0rGofJ1qOYSTNcc55EbBT7uq3wx3
# mXhtVmtcCEr5ZKTkKKE1CxZvNPWdGWJUPC6e4uRfWHIhZcgCsJ+sozf5EeH5KrlF
# nxpjKKTavwfFP6XaGZGWUG8TZaiTogRoAlqcevbiqioUz1Yt4FRK53P6ovnUfANj
# IgM9JDdJ4e0qiDRm5sOTiEQtBLGd9Vhd1MadxoGcHrRCsS5rO9yhv2fjJHrmlQ0E
# IXmp4DhDBieKUGR+eZ4CNE3ctW4uvSDQVeSp9h1SaPV8UWEfyTxgGjOsRpeexIve
# R1MPTVf7gt8hY64XNPO6iyUGsEgt8c2PxF87E+CO7A28TpjNq5eLiiunhKbq0Xbj
# kNoU5JhtYUrlmAbpxRjb9tSreDdtACpm3rkpxp7AQndnI0Shu/fk1/rE3oWsDqMX
# 3jjv40e8KN5YsJBnczyWB4JyeeFMW3JBfdeAKhzohFe8U5w9WuvcP1E8cIxLoKSD
# zCCBOu0hWdjzKNu8Y5SwB1lt5dQhABYyzR3dxEO/T1K/BVF3rV69AgMBAAGjggIb
# MIICFzAOBgNVHQ8BAf8EBAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYE
# FGtpKDo1L0hjQM972K9J6T7ZPdshMFQGA1UdIARNMEswSQYEVR0gADBBMD8GCCsG
# AQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVw
# b3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAwe
# CgBTAHUAYgBDAEEwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTIftJqhSob
# yhmYBAcnz1AQT2ioojCBhAYDVR0fBH0wezB5oHegdYZzaHR0cDovL3d3dy5taWNy
# b3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0JTIwSWRlbnRpdHklMjBWZXJp
# ZmljYXRpb24lMjBSb290JTIwQ2VydGlmaWNhdGUlMjBBdXRob3JpdHklMjAyMDIw
# LmNybDCBlAYIKwYBBQUHAQEEgYcwgYQwgYEGCCsGAQUFBzAChnVodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMElkZW50aXR5
# JTIwVmVyaWZpY2F0aW9uJTIwUm9vdCUyMENlcnRpZmljYXRlJTIwQXV0aG9yaXR5
# JTIwMjAyMC5jcnQwDQYJKoZIhvcNAQEMBQADggIBAF+Idsd+bbVaFXXnTHho+k7h
# 2ESZJRWluLE0Oa/pO+4ge/XEizXvhs0Y7+KVYyb4nHlugBesnFqBGEdC2IWmtKMy
# S1OWIviwpnK3aL5JedwzbeBF7POyg6IGG/XhhJ3UqWeWTO+Czb1c2NP5zyEh89F7
# 2u9UIw+IfvM9lzDmc2O2END7MPnrcjWdQnrLn1Ntday7JSyrDvBdmgbNnCKNZPmh
# zoa8PccOiQljjTW6GePe5sGFuRHzdFt8y+bN2neF7Zu8hTO1I64XNGqst8S+w+RU
# die8fXC1jKu3m9KGIqF4aldrYBamyh3g4nJPj/LR2CBaLyD+2BuGZCVmoNR/dSpR
# Cxlot0i79dKOChmoONqbMI8m04uLaEHAv4qwKHQ1vBzbV/nG89LDKbRSSvijmwJw
# xRxLLpMQ/u4xXxFfR4f/gksSkbJp7oqLwliDm/h+w0aJ/U5ccnYhYb7vPKNMN+SZ
# DWycU5ODIRfyoGl59BsXR/HpRGtiJquOYGmvA/pk5vC1lcnbeMrcWD/26ozePQ/T
# WfNXKBOmkFpvPE8CH+EeGGWzqTCjdAsno2jzTeNSxlx3glDGJgcdz5D/AAxw9Sdg
# q/+rY7jjgs7X6fqPTXPmaCAJKVHAP19oEjJIBwD1LyHbaEgBxFCogYSOiUIr0Xqc
# r1nJfiWG2GwYe6ZoAF1bMIIHnjCCBYagAwIBAgITMwAAAD8EGul+bSf+6wAAAAAA
# PzANBgkqhkiG9w0BAQwFADBhMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUHVibGljIFJTQSBU
# aW1lc3RhbXBpbmcgQ0EgMjAyMDAeFw0yNDA0MTgxNzU5MTJaFw0yNTA0MTcxNzU5
# MTJaMIHiMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYD
# VQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNV
# BAsTHVRoYWxlcyBUU1MgRVNOOkY1RDYtOTZENi05MDlFMTUwMwYDVQQDEyxNaWNy
# b3NvZnQgUHVibGljIFJTQSBUaW1lIFN0YW1waW5nIEF1dGhvcml0eTCCAiIwDQYJ
# KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKa8dtFVWahBfvb8Imntb/a5r6uYFchb
# gMupGX5W57MjhZ1hN8myyIxVJluIMPBrR0oUps41qvi/ddjl9G4mmBx2JH7yQtd3
# zUbmRm9HAa1JATHViEuo0m3CR/0QcTITSu1g+Efz04sl5RdwtBwc+3pKBHbPCL7A
# 4NZHGJEKwd+KKGJMVhX4N0/rY86Wrp+oJxEwbATYKeiW6cICnoomwB0vZZ2NaSO3
# 0eR/VbTMGemJVZjIagQ51h7gMzu4nmKvPcCDTt7VkOg+ApsvEpYWZ+LDEJ3pXVgN
# cVA8QmEBkigQIpHALyQkHWQ4BCfssBGqVwdoibLpaQyiTdQVbbA7lPVuq3+MEWw6
# 8Y9vyz62iLGx7fzkh8NfKlvpEMNhwIb3gIuz+CPJ302oRzNqtzR/0kx3NsmaeEaF
# hBWEvSqM7gDZpgFnEx9eWISBtK5yhRGETEHiV4gum3sl8KzEV0abgwOoihK+hikg
# /jOMM2vD53LD5MAEtmS8i6DPsAUMx11uYivswI7/hG4qO03yJNGl2bfNyEToWIkb
# m3uc89earhkvw/4FSE7MTV2lUVya65cCh2hkcU1uxEf0IHbSXlbXfYAg8fjmVFtC
# PnhNU05GesLhP9DT8da85oq/DWghH8FK+j6qzFc4JY8u55gQGSAgMamlKUnUtEHx
# hecSZGNMQWtzAgMBAAGjggHLMIIBxzAdBgNVHQ4EFgQUAfT7a5UsL6nNawk3eZDY
# nfyU4tcwHwYDVR0jBBgwFoAUa2koOjUvSGNAz3vYr0npPtk92yEwbAYDVR0fBGUw
# YzBhoF+gXYZbaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWlj
# cm9zb2Z0JTIwUHVibGljJTIwUlNBJTIwVGltZXN0YW1waW5nJTIwQ0ElMjAyMDIw
# LmNybDB5BggrBgEFBQcBAQRtMGswaQYIKwYBBQUHMAKGXWh0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwUHVibGljJTIwUlNB
# JTIwVGltZXN0YW1waW5nJTIwQ0ElMjAyMDIwLmNydDAMBgNVHRMBAf8EAjAAMBYG
# A1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDBmBgNVHSAEXzBd
# MFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jv
# c29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wCAYGZ4EMAQQCMA0G
# CSqGSIb3DQEBDAUAA4ICAQCNWqktJm2w5HuDNGBCDvJlZ8xgXijqyOzQMAaI8SOB
# UWzzGbw1aFqxW2jaKj7c+oiHTFL50J07OdUnCXvNOcjfV/4gcpxEi7vkwDI8Kbqq
# dnG15xVYhpe382geFXlIk9qnhe2+Rd3KTSnSfSSune4J0cb+V1L6QnWdqJqNvnAk
# Jln4mjoaE1diUMh+PII4wxGydwoq7nyRPjsQ3cLndkotwJ+qrQbBGR+gJzC3II2G
# hkwB34vwvXyPONx9MRTWAnW6+KoCoD3SEST6oBXxglje/oTh0Z8Fj+i2ZCUwjh4/
# wU0hB5pLAyHH5XyMewX/M69kfppzj5rwEKSi/wTXfFrUYT/JHIf5Bpzjlnjp4nMz
# Kdm7UJF+bwZ3edS6nZAVmUZrtHcucyCcP3kmDw+BuLxTFNLeJ55KzuclwGZD8QVM
# j0yFubD8ROsnHcJJ2YGtdFFNR+CIzHWe+n5nijI+mRRwkMa22lgueQ8RXcXOkkgS
# o73rpWW1amLnXAseYNQ6s7ETrNXMh4pN6rNbhUdEZnFzYMQL4AqzjkZ1uRrPriOo
# hiycL3eiNdUABxwcmlhENORq+tZgGDupR97XiGDmv6klWoYhN7OE9tZyFcXkZvRZ
# qDMaUK6VHOX1V4MywWF67iLRjQAb9PAvscfRq+Cz9gAMOsWoMjO0Inp9VljmTQ02
# EjGCBswwggbIAgEBMHgwYTELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGlt
# ZXN0YW1waW5nIENBIDIwMjACEzMAAAA/BBrpfm0n/usAAAAAAD8wDQYJYIZIAWUD
# BAIBBQCgggQlMBEGCyqGSIb3DQEJEAIPMQIFADAaBgkqhkiG9w0BCQMxDQYLKoZI
# hvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTI0MDgwNzEzNTExMVowLwYJKoZIhvcN
# AQkEMSIEIM+gdRobdjya7wP2j86hNo531rw+k/GcjyeEnFlcbBSSMIG5BgsqhkiG
# 9w0BCRACLzGBqTCBpjCBozCBoAQgK+TBZw0Xa+Kw5WCBp7ZSNIfFKKfqCS/ru4Su
# nbA865owfDBlpGMwYTELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFB1YmxpYyBSU0EgVGltZXN0
# YW1waW5nIENBIDIwMjACEzMAAAA/BBrpfm0n/usAAAAAAD8wggLnBgsqhkiG9w0B
# CRACEjGCAtYwggLSoYICzjCCAsowggIzAgEBMIIBEKGB6KSB5TCB4jELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0
# IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNT
# IEVTTjpGNUQ2LTk2RDYtOTA5RTE1MDMGA1UEAxMsTWljcm9zb2Z0IFB1YmxpYyBS
# U0EgVGltZSBTdGFtcGluZyBBdXRob3JpdHmiIwoBATAHBgUrDgMCGgMVAOW0W4Bs
# cgUUs2LUmJukVDCfgFxKoGcwZaRjMGExCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBQdWJsaWMg
# UlNBIFRpbWVzdGFtcGluZyBDQSAyMDIwMA0GCSqGSIb3DQEBBQUAAgUA6l3mATAi
# GA8yMDI0MDgwNzEyMjQzM1oYDzIwMjQwODA4MTIyNDMzWjB3MD0GCisGAQQBhFkK
# BAExLzAtMAoCBQDqXeYBAgEAMAoCAQACAgySAgH/MAcCAQACAhEtMAoCBQDqXzeB
# AgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSCh
# CjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQADgYEAqBN9Gt8vh+93rGPEcsCakJrl
# CbFoAvkTB0wrKC1pdudYEGgScuEc7XpLQZZBI61z0CSfWXEedPJMNsmFukJGVK4J
# V1rarfn3xc9nKcpdK6y6OcSnI59r+R0miih0xNiPY8J8CB0ySX+3Ka0+G3jTjqOK
# vampvS2RYrH8PdzUEAIwDQYJKoZIhvcNAQEBBQAEggIAGkEgUGpQOMMfJWVrJ516
# lkJ0irByu4u2D+VOEBqwzKwnLweU4gywzWcl9BmevNvdsICKX9GUlnIM52PMQs3u
# aae5imaGUooQTGtqjW8zOz2NIzRcMj+7YJNjwccKx0Pnjlk0/zSoU2DvIJrqyKZ4
# qT1l/pSt3f/+NMinCAj/T2lbVCkdOBzfV62Lq8+vD4VsTzRUxQdSeAmo6O1/R7lL
# oN6Ub03F8j/p9eNDlQUy/1lY9e/PJWyXorqE6/uaZyPTct5j0A+lVcyrYHZJwAPN
# f7Az9XUvYlvnG1/Rm1LHevd9mePfJaLx08dvZHQbUD2V96QAz3TBZVxQ8l8cTFf+
# gB57vpc231ixoPaTL6nXU6UVLsnwK99fxfwO4+mdPifgFM6zzZ4UJch/H+Vwjwew
# vCyb/YAyl211WDE0QGgkMvCuFcM9KheMh/lACsu5v9FXHndpx8DzVdfMBbBl92HA
# FEsC78jmFBRWM//YjMxwTTONyS8hYsqMyiItbM+YuVdYzqGm5XFMUZ86VCDcQLd1
# ZSBb57BFGS7uBAmi6Kxl/K74JPdYPK+8+riYAgLuY3g1DfE2y+Obw2PIvqiLpC9U
# 5a/+9zisGo0dgUxznMndcx4spVvSP9QQwLoaJLHb/+wnWYUE0b2mqnF6rwk6UbWY
# n8Rjot4WtAYI8bSqfhFyvH4=
# SIG # End signature block
