//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "windows_devices_gpio_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioController::NativeOpenpin___BOOLEAN__I4,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioController::get_PinCount___I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::NativeIsDriveModeSupported___BOOLEAN__U1,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::NativeRead___WindowsDevicesGpioGpioPinValue__I4,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::NativeWrite___VOID__I4__U1,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::NativeSetDriveMode___VOID__I4__U1,
    NULL,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::get_DebounceTimeout___mscorlibSystemTimeSpan,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::set_DebounceTimeout___VOID__mscorlibSystemTimeSpan,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_windows_devices_gpio_native_Windows_Devices_Gpio_GpioPin::DisposeNative___VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Gpio =
{
    "Windows.Devices.Gpio", 
    0x6F1F070E,
    method_lookup
};

