// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.

#include "nano_esp32_cam.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeInit___nanoFrameworkEsp32CameraCameraInitResult,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeCapture___SZARRAY_U1,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeCaptureToBuffer___I4__SZARRAY_U1,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeGetSensorId___I4,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeGetSensorSetting___I4__nanoFrameworkEsp32CameraSensorSetting,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeSetSensorSetting___VOID__nanoFrameworkEsp32CameraSensorSetting__I4,
    Library_nano_esp32_cam_nanoFramework_Esp32_Camera_Esp32Camera::NativeDispose___VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Esp32_Camera =
{
    "nanoFramework.Esp32.Camera",
    0x313AFB2B,
    method_lookup,
    { 100, 0, 0, 0 }
};

// clang-format on
