//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef COM_SKYWORKSINC_NANOFRAMEWORK_DEVICES_C1_H
#define COM_SKYWORKSINC_NANOFRAMEWORK_DEVICES_C1_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

typedef enum __nfpack C1TransferStatus
{
    C1TransferStatus_UnknownError = 0,
} C1TransferStatus;

struct Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Bus
{
    static const int FIELD___syncLock = 1;

    NANOCLR_NATIVE_DECLARE(NativeTransmitWriteWithAddress___VOID__U2__U1__U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeTransmitReadWithAddress___VOID__U2__U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeTransmitRead___VOID__U2__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeTransmitWrite___VOID__U2__U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeTransmitWriteAddress___VOID__U2__U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeTransmitReadAddress___VOID__U2__SZARRAY_U1);

    //--//
};

struct Library_Com_SkyworksInc_NanoFramework_Devices_C1_Com_SkyworksInc_NanoFramework_Devices_C1_C1Exception
{
    static const int FIELD___status = 5;

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Com_SkyworksInc_NanoFramework_Devices_C1;

#endif // COM_SKYWORKSINC_NANOFRAMEWORK_DEVICES_C1_H
