#
# Copyright (c) 2020 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.
#

name: "Check clang-format"

on: [pull_request]

jobs:
  format:
    name: "Check clang-format"

    runs-on: ubuntu-latest

    steps:
    
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

    # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - name: "Output PR"
      run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
        PR: ${{ steps.findPr.outputs.pr }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: "Install clang-format-10"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-10

    - name: "Format Codes"
      run: |
        SRC=$(git diff --name-only --diff-filter=d $(git merge-base HEAD $BRANCH) | grep -E "\.\(c\|h\|hpp\|cpp\)\$")
        clang-format-10 -i -style=file $SRC
    
    - name: Check diff
      run: git diff --exit-code HEAD
    
    - name: Create Pull Request
      if: failure()
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "Automated fix of code style using project clang-format rules."
        title: "Fix code style for ${{ github.repository }}/${PR}"
        assignees: "${{ github.actor }}"
        branch: "auto-pr/clang-format/${PR}"

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Submitted PR with code style fixes - ${{ steps.cpr.outputs.pull-request-number }}"
