name: Build and push ESP32 image

env:
  GCR_IMAGE: ghcr.io/nanoframework/dev-container-esp32
  GCR_VERSION: v2.3
  GCR_FILE: .devcontainer/sources/Dockerfile.ESP32

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
    paths: [ .devcontainer/sources/Dockerfile.ESP32 ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_BUILD_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        file: ${{ env.GCR_FILE }}
        push: true # Will only build if this is not here
        tags: |
          ${{ env.GCR_IMAGE }}:${{ env.GCR_VERSION }}
          ${{ env.GCR_IMAGE }}:latest