//
// Copyright (c) 2017 The nanoFramework project contributors
// Portions Copyright (c) Microsoft Corporation.  All rights reserved.
// See LICENSE file in the project root for full license information.
//

#include "nf_dt_native.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_dt_native_System_DateTime::_ctor___VOID__I4__I4__I4__I4__I4__I4__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_dt_native_System_DateTime::get_Day___I4,
    Library_nf_dt_native_System_DateTime::get_DayOfWeek___SystemDayOfWeek,
    Library_nf_dt_native_System_DateTime::get_DayOfYear___I4,
    Library_nf_dt_native_System_DateTime::get_Hour___I4,
    NULL,
    Library_nf_dt_native_System_DateTime::get_Millisecond___I4,
    Library_nf_dt_native_System_DateTime::get_Minute___I4,
    Library_nf_dt_native_System_DateTime::get_Month___I4,
    Library_nf_dt_native_System_DateTime::get_Second___I4,
    NULL,
    NULL,
    Library_nf_dt_native_System_DateTime::get_Year___I4,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_dt_native_System_DateTime::DaysInMonth___STATIC__I4__I4__I4,
    NULL,
    Library_nf_dt_native_System_DateTime::get_UtcNow___STATIC__SystemDateTime,
    Library_nf_dt_native_System_DateTime::get_Today___STATIC__SystemDateTime,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_dt_native_System_Globalization_DateTimeFormat::FormatDigits___STATIC__STRING__I4__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_dt_native_nanoFramework_DateTime_RTC::Native_RTC_SetSystemTime___STATIC__BOOLEAN__I4__U1__U1__U1__U1__U1__U1,
    Library_nf_dt_native_nanoFramework_DateTime_RTC::Native_RTC_SetAlarm___STATIC__BOOLEAN__I4__U1__U1__U1__U1__U1__U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_DateTime =
{
    "System.DateTime", 
    0x09C5C479,
    method_lookup
};
